### ISSUE TITLE
Player gets kicked when another player places a factory block, due to sound event

### ISSUE THREAD

**Issue by purejosh** [matthewperiut/factory_blocks#2]
If a player places a block from Factory Blocks, while within another player's hearing distance, it will kick the other player. 

1.19.2 Fabric, server. lmk what else you need to look into this. 

![image](https://user-images.githubusercontent.com/70633949/197448913-53bfdf9b-2d26-45bf-af06-72f2abf2302f.png)

**Comment by matthewperiut** [comment]
Hey, I just fixed this and forgot to push a release, the updated mod will actually be Chisel itself, here's a link to the new version and the curse forge version (pending approval)
Use the GitHub link for now:
https://github.com/matthewperiut/Chisel-Fabric/releases/tag/v1.4.7
https://www.curseforge.com/minecraft/mc-mods/chisel-reborn/files/4047203

**Comment by purejosh** [comment]
Oh wow. Cool! I'll use those ones. :D 

Thanks!

**Comment by Swedz** [comment]
Issue persists on Chisel 1.4.7 and Factory Blocks 1.0.0 with Fabric 1.19.2 0.14.11.

Server generates the following error:
```
[07:49:56] [Netty Epoll Server IO #3/ERROR]: Error receiving packet 96
java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@636929a2' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
	at net.minecraft.class_2540.method_42065(class_2540.java:147) ~[server-intermediary.jar:?]
	at net.minecraft.class_2767.method_11052(class_2767.java:47) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:209) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10761(class_2535.java:201) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[07:49:56] [Netty Epoll Server IO #3/ERROR]: Exception occurred in netty pipeline
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@636929a2' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:209) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10761(class_2535.java:201) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@636929a2' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
	at net.minecraft.class_2540.method_42065(class_2540.java:147) ~[server-intermediary.jar:?]
	at net.minecraft.class_2767.method_11052(class_2767.java:47) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar:?]
	... 16 more
[07:49:56] [Server thread/INFO]: Swedz lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@636929a2' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
```

Client has no error.

**Comment by JackDainzh** [comment]
Assuming the fix the file in lib folder is not updated and used as implementation instead of a new one. Updated the file, will test with a friend of mine and report results.

**Comment by JackDainzh** [comment]
Update: didn't fix the issues, assuming it's the main mod which conflicts now on server side.

**Comment by JackDainzh** [comment]
Fixed in #3.

**Comment by mounderfod** [comment]
Issue continues to persist on 1.4.7
